### ISSUE TITLE
Bullseye als baseimage

### ISSUE THREAD

**Issue by DerDoubleD** [fhem/alexa-fhem-docker#18]
Hallo
Danke für die images!

Könnte man ein Image auf der Basis von bullseye bereitstellen?

**Comment by sidey79** [comment]
Ich schau mir mal an, ob Buster ohne Anpassungen funktioniert und anschließend würde ich auch Bullseye in Angriff nehmen.

**Comment by sidey79** [comment]
Buster wäre zum Testen verfügbar:

https://github.com/fhem/alexa-fhem-docker/pkgs/container/fhem%2Falexa-fhem/13695697?tag=2.0.0-beta

**Comment by DerDoubleD** [comment]
Funktioniert für mich! Vielen Dank!!!

**Comment by sidey79** [comment]
OK. Ist aber bisher nur auf Basis Buster und nicht bullseye :)

**Comment by DerDoubleD** [comment]
Das ist mir klar. Aber zumindest wird buster noch geupdatet. Und ich wollte nur feedback geben das es funktioniert.
Wenn du natürlich bullseye bereit stellst dann steige ich gerne um. 😉
