### ISSUE TITLE
sshautoconf error during container startup (home dir. permission error)

### ISSUE THREAD

**Issue by AlpenFlizzer** [fhem/alexa-fhem-docker#3]
Hello all,

when I try to spin up a container using the image fhem/alexa-fhem:latest or dev (08th Spet. 2019) with a configuration section for proxy connection (i.e. to use FhemConnector Alexa Skill) I get the following error in the docker log:

`...[9/8/2019, 1:50:36 PM] sshautoconf: *** Error: Your Homedirectory is writable by group/other. This will not work with SSH

[9/8/2019, 1:50:36 PM] sshautoconf: aborted with user homedir writable by group/other ('chmod 755 /alexa-fhem' required)

[9/8/2019, 1:50:36 PM] *** SSH: proxy configuration failed: user homedir writable by group/other ('chmod 755 /alexa-fhem' required)...`

From what I can see, the FHEM instance in another container is successfully connected and some devices are found, however the proxy configuration fails.

Does anyone else experience this problem?

Thank you for your help!

Regards Sascha

For reference my config.json:

`{ "sshproxy" : {

      "description" : "FHEM Connector",

      "ssh" : "/usr/bin/ssh"

  },

  "connections": [

    {

      "name": "FHEM",

      "filter": "alexaName=..*",

      "port": "******",

      "server": "*******",

      "auth": {"**********"}

    }

  ]

}`

**Comment by jpawlowski** [comment]
That means that the FHEM directory you are mounting into the container has improper directory permissions (and it even says how you can fix it yourself).

This image is a somewhat behind the innovations that were introduced to [fhem/fhem-docker](https://github.com/fhem/fhem-docker) during the last month, including directory and file permission handling that were actually added just a couple of days ago.

If you wish, you may send in a pull request with improvements for this dedicated image as well.
Note that the alexa-fhem author does not seem to develop it for standalone setup as a priority. In fact I recommend you to use the built-in alexa-fhem capablities of fhem/fhem-docker instead. There is no real point in increased security anymore when using the FHEM proxy service.

**Comment by AlpenFlizzer** [comment]
Thank you for your quick answer.

At first I wanted to say, that I really appreciate your great work with the fhem docker container.
However, for me it is important to keep things seperated since I thought, this was the basic idea of Docker... (at least among other ideas) ...additionally I am a nerd with an obsession for order and cleanness. :-D

I applied all changes you have done in the fhem docker repo since [commit ](https://github.com/fhem/fhem-docker/commit/d31daf39d20cde1e56a612d9d0bda606beaf6da7), now also the alexa-fhem-docker image is working.

Here is what is working:
In FHEM I can see that alexa-fhem is connected. (alexa-fhem 0.5.29)
I get a ProxyKey (and all other stuff like bearerToken etc.) and the FhemConnector Skill is also working. (everything is green like described in the [FhemConnector wiki](https://wiki.fhem.de/wiki/FHEM_Connector_f%C3%BCr_Amazon_Alexa) )
I have tested one device (Z-Wave switch to switch on/off light) which is found by Alexa and can successfully be controlled by Alexa.

Here is what is not working:
I cannot control alexa-fhem from FHEM cmd-line (i.e. restart, stop, etc.) - Do you know something about the attr "alexaFHEM-host"?
docker ps still tells me that the container is unhealthy, although it is running and the log shows no errors.

Do you have any ideas regarding the not working things?

Thank you again!

Regards Sascha

**Comment by jpawlowski** [comment]
can you create the pull request?

Like I was saying, alexa-fhem was not designed by the author to remotely control start/stop of the process, it is something that needs to be handled by Docker and that's what you chose to go for. Putting an SSH server into that very same alexa-fhem-docker container does not make sense, for the reason you just explained yourself.

The health check script is likely to be updated but first check if you had fulfilled all the requirements that you would also need to have for the regular fhem-docker container (like having a telnet device in FHEM, listening on localhost, so that the script is able to connect to the FHEM process).
